### ISSUE TITLE
cart.service.ts

### ISSUE THREAD

**Issue by VZhyrytskiy** [amakarankau/LearnAngular#9]
addToCart(
    product: Partial<Product>, // { id: number, name: string, price: number },
Можно использовать Partial, если нужно подмножество полей модели Product. Правда, нет гарантии, что там будет id, name, price. Можно, конечно, расширить модель. Описать базовый тип с этими полями и расширить дополнительными. Это все альтернативы.

**Comment by amakarankau** [comment]
Спасибо рассмотрю, но пока оставлю как есть. Добавлял полный Product сюда после того как понадобилось в корзине какое-то поле из него вытащить. До этого была модель просто с именем продукта. Потом подумал,  что неизвестно какой функционал придется имплементить и что понадобится в корзине, поэтому добавил весь объект. В финале когда все определится по нужным полям, если будет время попробую оптимизировать.
